<?php
$block_get_data = $block->getMetaData();
$get_metaData = $block_get_data['metadata'];
$default_sku_value = $block_get_data['sku_selected'];
$default_image_role_value = $block_get_data['image_role_selected'];
$default_image_alt_text = $block_get_data['image_alt_text'];
?>

<form name="metaproperty" action="<?= $block->escapeUrl($block->getSubmitUrl()); ?>" method="post"
    enctype="multipart/form-data">
    <?= $block->getBlockHtml('formkey');
    ?>
    <div class="main_container dear-stock-sec">
        <div class="main_header_master admin__data-grid-wrap">
            <div class="main_container_masterdata admin__data-grid-wrap product-imp-sec">
                <label> <strong>The Meta Property Configration For the SKU:-</strong> </label> <br><br>
                <div class="form-check form-check-inline" style="float: left;width: 100%;">

                    <label class="form-check-label">
                        <input type="hidden" name="system_slug[]" value="sku" />
                        <label> <strong>Property List:-</strong> </label> <br><br>
                        <select class="selectbox_item" id="bynder_property" name="select_meta_tag[]">
                            <option value="0">Select The option</option>

                            <?php
                            if (count($get_metaData) > 0) {
                                foreach ($get_metaData as $v) {
                                    $checked = "";
                                    if ($default_sku_value == $v["name"]) {
                                        $checked = "selected";
                                    }
                                    ?>
                                    <option value="<?= $block->escapeHtml($v['name']); ?>"
                                        <?= $block->escapeHtml($checked); ?> >
                                        <?= $block->escapeHtml($v['label']); ?>
                                    </option>
                                    <?php
                                }
                            }
                            ?>
                        </select>
                    </label>

                </div>
                <hr>
                <label> <strong> The Meta Property Configration For the Image Role :-</strong> </label> <br><br>
                <div class="form-check form-check-inline" style="float: left;width: 100%;">

                    <label class="form-check-label">
                        <label> <strong>Property List:-</strong> </label> <br><br>
                        <input type="hidden" name="system_slug[]" value="image_role" />
                        <select class="selectbox_item" id="bynder_property_image_role" name="select_meta_tag[]">
                            <option value="0">Select The option</option>

                            <?php foreach ($get_metaData as $v) {
                                $checked = "";
                                if ($default_image_role_value == $v["name"]) {
                                    $checked = "selected";
                                }
                                ?>
                                <option value="<?= $block->escapeHtml($v['name']); ?>"
                                    <?= $block->escapeHtml($checked); ?>>
                                    <?= $block->escapeHtml($v['label']); ?>
                                </option>
                                <?php
                            } ?>
                        </select>
                    </label>
                </div>
                <hr>
                <label> <strong> The Meta Property Configration For the Alt Text :-</strong> </label> <br><br>
                <div class="form-check form-check-inline" style="float: left;width: 100%;">
                    <label class="form-check-label">
                        <label> <strong>Property List:-</strong> </label> <br><br>
                        <input type="hidden" name="system_slug[]" value="alt_text" />
                        <select class="selectbox_item" id="bynder_property_alt_tax" name="select_meta_tag[]">
                            <option value="0">Select The option</option>

                            <?php foreach ($get_metaData as $v) {
                                $checked = "";
                                if ($default_image_alt_text == $v["name"]) {
                                    $checked = "selected";
                                }
                                ?>
                                <option value="<?= $block->escapeHtml($v['name']); ?>" 
                                    <?= $block->escapeHtml($checked); ?>>
                                    <?= $block->escapeHtml($v['label']); ?>
                                </option>
                                <?php
                            } ?>
                        </select>
                    </label> 
                    <button type="submit" class="action- scalable primary" name="submit" id="btn_submit">
                        <span>
                            <?= $block->escapeHtml('Save SKU Property'); ?>
                        </span>
                    </button>
                </div>

            </div>
        </div>
    </div>

</form>
